### ISSUE TITLE
現在のエラー

### ISSUE THREAD

**Issue by tissya** [tissya/Blockchain_simulator#1]
Exception in thread "main" java.lang.NullPointerException
	at Blockchain.run(Blockchain.java:86)
	at Main.main(Main.java:11)

P.S
normaとnodesの値はしっかり入ってる模様

**Comment by tissya** [comment]
このコミットによって解決した
https://github.com/tissya/Blockchain_simulator/commit/8ccd9023d39a78f14b211cb40e191e82cf457910
